<?php
/*
 * phpComicDB config file - 2012
 */

// This is for PHP PEAR (why?)
// database url in the form
// driver://user:password@host/database
//define('DB_URL', "mysql://comicdb:comicdb@localhost/comicdb");

//define('DB_URL','localhost');
//define('DB_USER','comicdb');
//define('DB_PASS','comicdb');
//define('DB_NAME','comicdb');

define('DB_URL','207.210.200.134');
define('DB_USER','scfloyd_comicdb');
define('DB_PASS','28doVPrpJ');
define('DB_NAME','scfloyd_comicdb');

// prefixed to the title of every HTML page
define('HTML_TITLE_PREFIX', 'jsComicDB');

// separates the title prefix and other components of the page title
define('HTML_TITLE_SEPARATOR', ' | ');
